(test
 (name test_violet)
 (deps
  (source_tree ../example)
  (source_tree fixtures))
 (preprocess
  (pps ppx_deriving.show))
 (libraries
  violet_common
  violet_surface
  violet_elab
  violet_kernel
  violet_project
  asai
  eio
  eio_main
  yuujinchou
  bwd
  unix
  tsort))

(test
 (name test_parser)
 (libraries violet_surface violet_elab violet_kernel asai))

(test
 (name test_interactive)
 (libraries violet_interactive violet_surface violet_elab violet_kernel asai))
