(* Stylesheet for woven Violet code: token colours, definition/use anchors, and
   the pure-CSS hover tooltip. Shipped as [violet.css] next to the woven output and
   linked once from the tr-notes site template. *)

let stylesheet =
  {css|/* Violet literate highlighting — generated by `violet weave`. */
pre .vt-kw     { color: #7c4dff; font-weight: 600; }
pre .vt-op     { color: #00897b; }
pre .vt-punct  { color: #607d8b; }
pre .vt-str    { color: #c62828; }
pre .vt-id     { color: inherit; }
pre .vt-binder { color: #1565c0; }

pre .vt-def {
  color: #1565c0;
  font-weight: 600;
}
pre a.vt-use {
  color: #1565c0;
  text-decoration: none;
  border-bottom: 1px dotted rgba(21, 101, 192, 0.5);
}
pre a.vt-use:hover { border-bottom-style: solid; }

pre .vt-goal {
  background: rgba(220, 160, 0, 0.18);
  border-bottom: 1px dashed #c89000;
}

/* Hover tooltips. The annotated token is the positioning context; its inner
   .vt-tip is shown on hover. */
pre .vt-def, pre a.vt-use, pre .vt-binder, pre .vt-goal { position: relative; }
pre .vt-tip {
  display: none;
  position: absolute;
  left: 0;
  bottom: 1.5em;
  z-index: 10;
  white-space: pre;
  padding: 0.3em 0.5em;
  border-radius: 3px;
  background: #1d2433;
  color: #e6e6e6;
  font-size: 0.85em;
  font-weight: 400;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
  pointer-events: none;
}
pre .vt-def:hover > .vt-tip,
pre a.vt-use:hover > .vt-tip,
pre .vt-binder:hover > .vt-tip,
pre .vt-goal:hover > .vt-tip { display: block; }
|css}
;;
